// apps/nuxt-app/pages/image-generate.vue
<template>
  <div class="flex flex-col lg:flex-row min-h-screen">
    <!-- Left Panel - Input Form -->
    <div class="w-full lg:w-1/2 border-r border-border bg-background p-6 overflow-y-auto">
      <div class="max-w-2xl mx-auto space-y-6">
        <!-- Header -->
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold">{{ $t('ai.image.title') }}</h1>
            <p class="text-sm text-muted-foreground mt-1">{{ $t('ai.image.description') }}</p>
          </div>
          <div v-if="creditBalance !== null" class="text-sm text-muted-foreground">
            {{ $t('ai.image.credits') }}: <span class="font-semibold text-foreground">{{ creditBalance }}</span>
          </div>
        </div>

        <!-- Provider & Model Selection -->
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>{{ $t('ai.image.providers.title') }}</Label>
            <Select v-model="provider">
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="p in Object.keys(imageConfig.availableModels)" :key="p" :value="p">
                  {{ $t(`ai.image.providers.${p}`) || p }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div class="space-y-2">
            <Label>Model</Label>
            <Select v-model="model">
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="m in availableModels" :key="m" :value="m">
                  {{ getModelDisplayName(m) }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <!-- Prompt -->
        <div class="space-y-2">
          <Label>{{ $t('ai.image.prompt') }}</Label>
          <Textarea
            v-model="prompt"
            :placeholder="$t('ai.image.promptPlaceholder')"
            class="min-h-[120px] resize-y"
          />
        </div>

        <!-- Additional Settings Toggle -->
        <div>
          <Button
            variant="ghost"
            class="w-full justify-between"
            @click="showSettings = !showSettings"
          >
            <span>{{ $t('ai.image.settings.title') }}</span>
            <ChevronUp v-if="showSettings" class="h-4 w-4" />
            <ChevronDown v-else class="h-4 w-4" />
          </Button>
        </div>

        <!-- Additional Settings -->
        <div v-if="showSettings" class="space-y-6 border rounded-lg p-4 bg-muted/30">
          <!-- Negative Prompt -->
          <div class="space-y-2">
            <Label>{{ $t('ai.image.negativePrompt') }}</Label>
            <Textarea
              v-model="negativePrompt"
              :placeholder="$t('ai.image.negativePromptPlaceholder')"
              class="min-h-[80px] resize-y"
            />
            <p class="text-xs text-muted-foreground">{{ $t('ai.image.negativePromptHint') }}</p>
          </div>

          <!-- Image Size -->
          <div class="space-y-2">
            <Label>{{ $t('ai.image.settings.imageSize') }}</Label>
            <Select v-model="size">
              <SelectTrigger>
                <SelectValue placeholder="Select size" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="s in availableSizes" :key="s.value" :value="s.value">
                  {{ s.label }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <!-- Fal-specific settings -->
          <template v-if="provider === 'fal'">
            <!-- Inference Steps -->
            <div class="space-y-2">
              <div class="flex justify-between">
                <Label>{{ $t('ai.image.settings.numInferenceSteps') }}</Label>
                <span class="text-sm text-muted-foreground">{{ numInferenceSteps }}</span>
              </div>
              <Slider
                :model-value="[numInferenceSteps]"
                @update:model-value="(v) => { if (v && v[0] !== undefined) numInferenceSteps = v[0] }"
                :min="1"
                :max="50"
                :step="1"
              />
              <p class="text-xs text-muted-foreground">{{ $t('ai.image.settings.numInferenceStepsHint') }}</p>
            </div>

            <!-- Guidance Scale -->
            <div class="space-y-2">
              <div class="flex justify-between">
                <Label>{{ $t('ai.image.settings.guidanceScale') }}</Label>
                <span class="text-sm text-muted-foreground">{{ guidanceScale }}</span>
              </div>
              <Slider
                :model-value="[guidanceScale]"
                @update:model-value="(v) => { if (v && v[0] !== undefined) guidanceScale = v[0] }"
                :min="1"
                :max="20"
                :step="0.5"
              />
              <p class="text-xs text-muted-foreground">{{ $t('ai.image.settings.guidanceScaleHint') }}</p>
            </div>
          </template>

          <!-- Seed -->
          <div class="space-y-2">
            <Label>{{ $t('ai.image.settings.seed') }}</Label>
            <div class="flex gap-2">
              <Input
                v-model="seed"
                :placeholder="$t('ai.image.settings.random')"
                class="flex-1"
              />
              <Button variant="outline" size="icon" @click="randomizeSeed">
                <RefreshCw class="h-4 w-4" />
              </Button>
            </div>
            <p class="text-xs text-muted-foreground">{{ $t('ai.image.settings.seedHint') }}</p>
          </div>

          <!-- Qwen-specific settings -->
          <template v-if="provider === 'qwen'">
            <div class="flex items-center justify-between">
              <div>
                <Label>{{ $t('ai.image.settings.promptExtend') }}</Label>
                <p class="text-xs text-muted-foreground">{{ $t('ai.image.settings.promptExtendHint') }}</p>
              </div>
              <Switch v-model:checked="promptExtend" />
            </div>

            <div class="flex items-center justify-between">
              <div>
                <Label>{{ $t('ai.image.settings.watermark') }}</Label>
                <p class="text-xs text-muted-foreground">{{ $t('ai.image.settings.watermarkHint') }}</p>
              </div>
              <Switch v-model:checked="watermark" />
            </div>
          </template>
        </div>

        <!-- Generate Button -->
        <Button
          class="w-full"
          size="lg"
          :disabled="isGenerating || !prompt.trim()"
          @click="handleGenerate"
        >
          <template v-if="isGenerating">
            <RefreshCw class="mr-2 h-4 w-4 animate-spin" />
            {{ $t('ai.image.generating') }}
          </template>
          <template v-else>
            <ImageIcon class="mr-2 h-4 w-4" />
            {{ $t('ai.image.generate') }}
          </template>
        </Button>
      </div>
    </div>

    <!-- Right Panel - Result -->
    <div class="w-full lg:w-1/2 bg-muted/30 p-6 flex flex-col">
      <div class="flex items-center justify-between mb-4">
        <div class="flex items-center gap-2">
          <h2 class="text-lg font-semibold">{{ $t('ai.image.result') }}</h2>
          <span class="text-xs bg-muted px-2 py-1 rounded">
            {{ isGenerating ? $t('ai.image.generating') : $t('ai.image.idle') }}
          </span>
        </div>
      </div>

      <!-- Result Display -->
      <div class="flex-1 flex items-center justify-center bg-background rounded-lg border border-border min-h-[400px] relative overflow-hidden">
        <template v-if="isGenerating">
          <div class="flex flex-col items-center gap-4">
            <RefreshCw class="h-8 w-8 animate-spin text-primary" />
            <p class="text-muted-foreground">{{ $t('ai.image.generating') }}</p>
          </div>
        </template>
        <template v-else-if="result">
          <img
            :src="result.imageUrl"
            alt="Generated image"
            class="max-w-full max-h-full object-contain"
          />
        </template>
        <template v-else-if="error">
          <div class="text-center text-destructive">
            <p class="font-medium">{{ $t('ai.image.errors.generationFailed') }}</p>
            <p class="text-sm mt-1">{{ error }}</p>
          </div>
        </template>
        <template v-else>
          <div class="text-center text-muted-foreground">
            <ImageIcon class="h-12 w-12 mx-auto mb-4 opacity-50" />
            <p>{{ $t('ai.image.idle') }}</p>
          </div>
        </template>
      </div>

      <!-- Actions -->
      <div v-if="result" class="mt-4 space-y-4">
        <p class="text-sm text-muted-foreground">{{ $t('ai.image.whatNext') }}</p>
        <Button class="w-full" @click="handleDownload">
          <Download class="mr-2 h-4 w-4" />
          {{ $t('ai.image.download') }}
        </Button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { ImageIcon, Download, RefreshCw, ChevronDown, ChevronUp } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { config } from '@config'

import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Slider } from '@/components/ui/slider'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { getImageSizesForProvider } from '@libs/ai'

type ImageProviderName = 'qwen' | 'fal' | 'openai'

interface GenerationResult {
  imageUrl: string
  width?: number
  height?: number
  provider: string
  model: string
  seed?: number
}

// SEO and metadata
const { t: $t, tm } = useI18n()
const localePath = useLocalePath()

useSeoMeta({
  title: $t('ai.image.metadata.title'),
  description: $t('ai.image.metadata.description'),
  keywords: $t('ai.image.metadata.keywords')
})

// Image configuration
const imageConfig = config.aiImage

// Provider and model state
const provider = ref<ImageProviderName>(imageConfig.defaultProvider as ImageProviderName)
const model = ref<string>(imageConfig.defaultModels[imageConfig.defaultProvider as keyof typeof imageConfig.defaultModels])

// Form state
const prompt = ref($t('ai.image.defaultPrompt'))
const negativePrompt = ref('')
const size = ref('')
const numInferenceSteps = ref<number>(imageConfig.defaults.numInferenceSteps)
const guidanceScale = ref<number>(imageConfig.defaults.guidanceScale)
const seed = ref('random')
const promptExtend = ref(imageConfig.defaults.promptExtend)
const watermark = ref(imageConfig.defaults.watermark)

// UI state
const showSettings = ref(false)
const isGenerating = ref(false)
const result = ref<GenerationResult | null>({
  imageUrl: 'https://placehold.co/1024x1024.png?text=Demo+Image',
  provider: imageConfig.defaultProvider,
  model: imageConfig.defaultModels[imageConfig.defaultProvider as keyof typeof imageConfig.defaultModels],
})
const error = ref<string | null>(null)
const creditBalance = ref<number | null>(null)

// Computed properties
const availableModels = computed(() => {
  return imageConfig.availableModels[provider.value as keyof typeof imageConfig.availableModels] || []
})

const availableSizes = computed(() => {
  return getImageSizesForProvider(provider.value)
})

// Get model translations as an object
const modelTranslations = computed(() => {
  return tm('ai.image.models') as Record<string, string>
})

// Helper function to get model display name
const getModelDisplayName = (modelKey: string) => {
  return modelTranslations.value?.[modelKey] || modelKey
}

// Watch provider changes
watch(provider, (newProvider) => {
  const defaultModel = imageConfig.defaultModels[newProvider as keyof typeof imageConfig.defaultModels]
  model.value = defaultModel
  
  // Set default size for the provider
  const sizes = getImageSizesForProvider(newProvider)
  if (sizes.length > 0) {
    const defaultSize = sizes.find((s: { value: string }) => s.value.includes('1:1') || s.value.includes('1328'))
    size.value = defaultSize?.value || sizes[0].value
  }
})

// Check credit balance on mount
onMounted(async () => {
  await checkCreditBalance()
  // Set initial size
  if (availableSizes.value.length > 0) {
    const defaultSize = availableSizes.value.find((s: { value: string }) => s.value.includes('1:1') || s.value.includes('1328'))
    size.value = defaultSize?.value || availableSizes.value[0].value
  }
})

const checkCreditBalance = async () => {
  try {
    const response = await $fetch<{ credits?: { balance?: number } }>('/api/credits/status')
    creditBalance.value = response?.credits?.balance || 0
  } catch (err) {
    console.error('Failed to check credit balance:', err)
  }
}

const handleGenerate = async () => {
  if (!prompt.value.trim()) {
    toast.error($t('ai.image.errors.invalidPrompt'))
    return
  }

  isGenerating.value = true
  error.value = null

  try {
    const response = await $fetch<{
      success: boolean
      data: GenerationResult
      credits?: { remaining: number }
      message?: string
    }>('/api/image-generate', {
      method: 'POST',
      body: {
        prompt: prompt.value.trim(),
        provider: provider.value,
        model: model.value,
        negativePrompt: negativePrompt.value.trim() || undefined,
        size: provider.value === 'fal' ? undefined : size.value,
        aspectRatio: provider.value === 'fal' ? size.value : undefined,
        seed: seed.value === 'random' ? undefined : parseInt(seed.value, 10),
        promptExtend: provider.value === 'qwen' ? promptExtend.value : undefined,
        watermark: provider.value === 'qwen' ? watermark.value : undefined,
        numInferenceSteps: provider.value === 'fal' ? numInferenceSteps.value : undefined,
        guidanceScale: provider.value === 'fal' ? guidanceScale.value : undefined,
      },
    })

    result.value = response.data
    if (response.credits?.remaining !== undefined) {
      creditBalance.value = response.credits.remaining
    }
    toast.success($t('ai.image.generatedSuccessfully'))
  } catch (err: any) {
    const statusCode = err?.statusCode || err?.response?.status
    if (statusCode === 402) {
      toast.error($t('ai.image.errors.insufficientCredits'), {
        description: $t('ai.image.errors.insufficientCreditsDescription'),
        action: {
          label: $t('common.viewPlans') || 'View Plans',
          onClick: () => navigateTo(localePath('/pricing'))
        }
      })
      return
    }
    
    const message = err?.data?.message || err?.message || $t('ai.image.errors.unknownError')
    error.value = message
    toast.error($t('ai.image.errors.generationFailed'), { description: message })
  } finally {
    isGenerating.value = false
  }
}

const handleDownload = async () => {
  if (!result.value?.imageUrl) return

  try {
    const response = await fetch(result.value.imageUrl)
    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `image-${Date.now()}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
  } catch (err) {
    // If fetch fails (e.g., CORS), open in new tab
    window.open(result.value.imageUrl, '_blank')
  }
}

const randomizeSeed = () => {
  seed.value = Math.floor(Math.random() * 2147483647).toString()
}
</script>

// apps/next-app/app/[lang]/(root)/image-generate/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { ImageIcon, DownloadIcon, RefreshCwIcon, ChevronDownIcon, ChevronUpIcon } from 'lucide-react';
import { toast } from 'sonner';
import { useTranslation } from '@/hooks/use-translation';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { config } from '@config';
import { getImageSizesForProvider } from '@libs/ai';

type ImageProviderName = 'qwen' | 'fal' | 'openai';

interface GenerationResult {
  imageUrl: string;
  width?: number;
  height?: number;
  provider: string;
  model: string;
  seed?: number;
}

export default function ImageGeneratePage() {
  const { t, locale } = useTranslation();
  
  // Provider and model state
  const imageConfig = config.aiImage;
  const [provider, setProvider] = useState<ImageProviderName>(imageConfig.defaultProvider as ImageProviderName);
  const [model, setModel] = useState<string>(imageConfig.defaultModels[imageConfig.defaultProvider as keyof typeof imageConfig.defaultModels]);
  
  // Form state
  const [prompt, setPrompt] = useState(t.ai.image.defaultPrompt);
  const [negativePrompt, setNegativePrompt] = useState('');
  const [size, setSize] = useState<string>('');
  const [numInferenceSteps, setNumInferenceSteps] = useState<number>(imageConfig.defaults.numInferenceSteps);
  const [guidanceScale, setGuidanceScale] = useState<number>(imageConfig.defaults.guidanceScale);
  const [seed, setSeed] = useState<string>('random');
  const [promptExtend, setPromptExtend] = useState<boolean>(imageConfig.defaults.promptExtend);
  const [watermark, setWatermark] = useState<boolean>(imageConfig.defaults.watermark);
  
  // UI state
  const [showSettings, setShowSettings] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<GenerationResult | null>({
    imageUrl: 'https://placehold.co/1024x1024.png?text=Demo+Image',
    provider: imageConfig.defaultProvider,
    model: imageConfig.defaultModels[imageConfig.defaultProvider as keyof typeof imageConfig.defaultModels],
  });
  const [error, setError] = useState<string | null>(null);
  const [creditBalance, setCreditBalance] = useState<number | null>(null);
  
  // Get available sizes/aspect ratios for current provider
  const availableSizes = getImageSizesForProvider(provider);
  
  // Update model when provider changes
  useEffect(() => {
    const defaultModel = imageConfig.defaultModels[provider as keyof typeof imageConfig.defaultModels];
    setModel(defaultModel);
    // Set default size for the provider
    if (availableSizes.length > 0) {
      const defaultSize = availableSizes.find((s: { value: string }) => s.value.includes('1:1') || s.value.includes('1328'));
      setSize(defaultSize?.value || availableSizes[0].value);
    }
  }, [provider]);
  
  // Check credit balance on mount
  useEffect(() => {
    checkCreditBalance();
  }, []);
  
  const checkCreditBalance = async () => {
    try {
      const response = await fetch('/api/credits/status');
      const data = await response.json();
      setCreditBalance(data?.credits?.balance || 0);
    } catch (err) {
      console.error('Failed to check credit balance:', err);
    }
  };
  
  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error(t.ai.image.errors.invalidPrompt);
      return;
    }
    
    setIsGenerating(true);
    setError(null);
    
    try {
      const response = await fetch('/api/image-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: prompt.trim(),
          provider,
          model,
          negativePrompt: negativePrompt.trim() || undefined,
          size: provider === 'fal' ? undefined : size,
          aspectRatio: provider === 'fal' ? size : undefined,
          seed: seed === 'random' ? undefined : parseInt(seed, 10),
          promptExtend: provider === 'qwen' ? promptExtend : undefined,
          watermark: provider === 'qwen' ? watermark : undefined,
          numInferenceSteps: provider === 'fal' ? numInferenceSteps : undefined,
          guidanceScale: provider === 'fal' ? guidanceScale : undefined,
        }),
      });
      
      const data = await response.json();
      
      if (!response.ok) {
        if (response.status === 402) {
          toast.error(t.ai.image.errors.insufficientCredits, {
            description: t.ai.image.errors.insufficientCreditsDescription,
            action: {
              label: t.common?.viewPlans || 'View Plans',
              onClick: () => { window.location.href = `/${locale}/pricing`; }
            }
          });
          return;
        }
        throw new Error(data.message || t.ai.image.errors.generationFailed);
      }
      
      setResult(data.data);
      setCreditBalance(data.credits?.remaining);
      toast.success(t.ai.image.generatedSuccessfully);
      
    } catch (err) {
      const message = err instanceof Error ? err.message : t.ai.image.errors.unknownError;
      setError(message);
      toast.error(t.ai.image.errors.generationFailed, { description: message });
    } finally {
      setIsGenerating(false);
    }
  };
  
  const handleDownload = async () => {
    if (!result?.imageUrl) return;
    
    try {
      const response = await fetch(result.imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      // If fetch fails (e.g., CORS), open in new tab
      window.open(result.imageUrl, '_blank');
    }
  };
  
  const randomizeSeed = () => {
    setSeed(Math.floor(Math.random() * 2147483647).toString());
  };

  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      {/* Left Panel - Input Form */}
      <div className="w-full lg:w-1/2 border-r border-border bg-background p-6 overflow-y-auto">
        <div className="max-w-2xl mx-auto space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold">{t.ai.image.title}</h1>
              <p className="text-sm text-muted-foreground mt-1">{t.ai.image.description}</p>
            </div>
            {creditBalance !== null && (
              <div className="text-sm text-muted-foreground">
                {t.ai.image.credits}: <span className="font-semibold text-foreground">{creditBalance}</span>
              </div>
            )}
          </div>
          
          {/* Provider & Model Selection */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>{t.ai.image.providers.title}</Label>
              <Select value={provider} onValueChange={(v) => setProvider(v as ImageProviderName)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Object.keys(imageConfig.availableModels).map((p) => (
                    <SelectItem key={p} value={p}>
                      {t.ai.image.providers[p as keyof typeof t.ai.image.providers] || p}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label>Model</Label>
              <Select value={model} onValueChange={setModel}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {(imageConfig.availableModels[provider as keyof typeof imageConfig.availableModels] || []).map((m: string) => (
                    <SelectItem key={m} value={m}>
                      {(t.ai.image.models as Record<string, string>)[m] || m}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          
          {/* Prompt */}
          <div className="space-y-2">
            <Label>{t.ai.image.prompt}</Label>
            <Textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={t.ai.image.promptPlaceholder}
              className="min-h-[120px] resize-y"
            />
          </div>
          
          {/* Additional Settings Toggle */}
          <div>
            <Button
              variant="ghost"
              className="w-full justify-between"
              onClick={() => setShowSettings(!showSettings)}
            >
              <span>{t.ai.image.settings.title}</span>
              {showSettings ? <ChevronUpIcon className="h-4 w-4" /> : <ChevronDownIcon className="h-4 w-4" />}
            </Button>
          </div>
          
          {/* Additional Settings */}
          {showSettings && (
            <div className="space-y-6 border rounded-lg p-4 bg-muted/30">
              {/* Negative Prompt */}
              <div className="space-y-2">
                <Label>{t.ai.image.negativePrompt}</Label>
                <Textarea
                  value={negativePrompt}
                  onChange={(e) => setNegativePrompt(e.target.value)}
                  placeholder={t.ai.image.negativePromptPlaceholder}
                  className="min-h-[80px] resize-y"
                />
                <p className="text-xs text-muted-foreground">{t.ai.image.negativePromptHint}</p>
              </div>
              
              {/* Image Size */}
              <div className="space-y-2">
                <Label>{t.ai.image.settings.imageSize}</Label>
                <Select value={size} onValueChange={setSize}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select size" />
                  </SelectTrigger>
                  <SelectContent>
                    {availableSizes.map((s: { value: string; label: string }) => (
                      <SelectItem key={s.value} value={s.value}>
                        {s.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {/* Fal-specific settings */}
              {provider === 'fal' && (
                <>
                  {/* Inference Steps */}
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <Label>{t.ai.image.settings.numInferenceSteps}</Label>
                      <span className="text-sm text-muted-foreground">{numInferenceSteps}</span>
                    </div>
                    <Slider
                      value={[numInferenceSteps]}
                      onValueChange={([v]) => setNumInferenceSteps(v)}
                      min={1}
                      max={50}
                      step={1}
                    />
                    <p className="text-xs text-muted-foreground">{t.ai.image.settings.numInferenceStepsHint}</p>
                  </div>
                  
                  {/* Guidance Scale */}
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <Label>{t.ai.image.settings.guidanceScale}</Label>
                      <span className="text-sm text-muted-foreground">{guidanceScale}</span>
                    </div>
                    <Slider
                      value={[guidanceScale]}
                      onValueChange={([v]) => setGuidanceScale(v)}
                      min={1}
                      max={20}
                      step={0.5}
                    />
                    <p className="text-xs text-muted-foreground">{t.ai.image.settings.guidanceScaleHint}</p>
                  </div>
                </>
              )}
              
              {/* Seed */}
              <div className="space-y-2">
                <Label>{t.ai.image.settings.seed}</Label>
                <div className="flex gap-2">
                  <Input
                    value={seed}
                    onChange={(e) => setSeed(e.target.value)}
                    placeholder={t.ai.image.settings.random}
                    className="flex-1"
                  />
                  <Button variant="outline" size="icon" onClick={randomizeSeed}>
                    <RefreshCwIcon className="h-4 w-4" />
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">{t.ai.image.settings.seedHint}</p>
              </div>
              
              {/* Qwen-specific settings */}
              {provider === 'qwen' && (
                <>
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>{t.ai.image.settings.promptExtend}</Label>
                      <p className="text-xs text-muted-foreground">{t.ai.image.settings.promptExtendHint}</p>
                    </div>
                    <Switch checked={promptExtend} onCheckedChange={setPromptExtend} />
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>{t.ai.image.settings.watermark}</Label>
                      <p className="text-xs text-muted-foreground">{t.ai.image.settings.watermarkHint}</p>
                    </div>
                    <Switch checked={watermark} onCheckedChange={setWatermark} />
                  </div>
                </>
              )}
            </div>
          )}
          
          {/* Generate Button */}
          <Button
            className="w-full"
            size="lg"
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
          >
            {isGenerating ? (
              <>
                <RefreshCwIcon className="mr-2 h-4 w-4 animate-spin" />
                {t.ai.image.generating}
              </>
            ) : (
              <>
                <ImageIcon className="mr-2 h-4 w-4" />
                {t.ai.image.generate}
              </>
            )}
          </Button>
        </div>
      </div>
      
      {/* Right Panel - Result */}
      <div className="w-full lg:w-1/2 bg-muted/30 p-6 flex flex-col">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-semibold">{t.ai.image.result}</h2>
            <span className="text-xs bg-muted px-2 py-1 rounded">
              {isGenerating ? t.ai.image.generating : t.ai.image.idle}
            </span>
          </div>
        </div>
        
        {/* Result Display */}
        <div className="flex-1 flex items-center justify-center bg-background rounded-lg border border-border min-h-[400px] relative overflow-hidden">
          {isGenerating ? (
            <div className="flex flex-col items-center gap-4">
              <RefreshCwIcon className="h-8 w-8 animate-spin text-primary" />
              <p className="text-muted-foreground">{t.ai.image.generating}</p>
            </div>
          ) : result ? (
            <img
              src={result.imageUrl}
              alt="Generated image"
              className="max-w-full max-h-full object-contain"
            />
          ) : error ? (
            <div className="text-center text-destructive">
              <p className="font-medium">{t.ai.image.errors.generationFailed}</p>
              <p className="text-sm mt-1">{error}</p>
            </div>
          ) : (
            <div className="text-center text-muted-foreground">
              <ImageIcon className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>{t.ai.image.idle}</p>
            </div>
          )}
        </div>
        
        {/* Actions */}
        {result && (
          <div className="mt-4 space-y-4">
            <p className="text-sm text-muted-foreground">{t.ai.image.whatNext}</p>
            <Button onClick={handleDownload} className="w-full">
              <DownloadIcon className="mr-2 h-4 w-4" />
              {t.ai.image.download}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
