// apps/nuxt-app/pages/admin/users/[id]/index.vue
<template>
  <div class="container mx-auto py-10 px-5">
    <!-- Back link -->
    <div class="flex items-center mb-6">
      <NuxtLink to="/admin/users" class="text-primary hover:text-primary/80">
        ← {{ t('actions.backToList') }}
      </NuxtLink>
    </div>

    <!-- Page title -->
    <h1 class="text-3xl font-bold mb-6">
      {{ isEditMode ? t('admin.users.editUser') : t('admin.users.createUser') }}
    </h1>

    <!-- Error message -->
    <div v-if="errorMessage" class="mb-4 p-4 text-destructive bg-destructive/10 rounded-md">
      {{ errorMessage }}
    </div>

    <!-- Loading skeleton -->
    <div v-if="pending" class="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <Skeleton class="h-7 w-40 mb-2" />
          <Skeleton class="h-4 w-60" />
        </CardHeader>
        <CardContent class="space-y-4">
          <div v-for="i in 6" :key="i" class="space-y-2">
            <Skeleton class="h-5 w-24" />
            <Skeleton class="h-10 w-full" />
          </div>
        </CardContent>
        <CardFooter class="pt-6">
          <Skeleton class="h-10 w-32" />
        </CardFooter>
      </Card>
    </div>

    <!-- Form -->
    <form v-else @submit="onSubmit" class="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>{{ t('admin.users.form.title') }}</CardTitle>
          <CardDescription>{{ t('admin.users.form.description') }}</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <!-- Name field -->
          <div class="space-y-2">
            <Label for="name">{{ t('admin.users.form.labels.name') }}</Label>
            <Input 
              id="name"
              v-bind="nameAttrs"
              v-model="name"
              :placeholder="t('admin.users.form.placeholders.name')"
              :class="errors.name ? 'border-destructive' : ''"
            />
            <p v-if="errors.name" class="text-destructive text-sm">{{ errors.name }}</p>
          </div>
          
          <!-- Email field -->
          <div class="space-y-2">
            <Label for="email">{{ t('admin.users.form.labels.email') }}</Label>
            <Input 
              id="email"
              type="email"
              v-bind="emailAttrs"
              v-model="email"
              :disabled="isEditMode"
              :placeholder="t('admin.users.form.placeholders.email')"
              :class="errors.email ? 'border-destructive' : ''"
            />
            <p v-if="errors.email" class="text-destructive text-sm">{{ errors.email }}</p>
          </div>
          
          <!-- Password field (only for new users) -->
          <div v-if="!isEditMode" class="space-y-2">
            <Label for="password">{{ t('admin.users.form.labels.password') }}</Label>
            <Input 
              id="password"
              type="password"
              v-bind="passwordAttrs"
              v-model="password"
              :placeholder="t('admin.users.form.placeholders.password')"
              :class="errors.password ? 'border-destructive' : ''"
            />
            <p v-if="errors.password" class="text-destructive text-sm">{{ errors.password }}</p>
          </div>
          
          <!-- Role field -->
          <div class="space-y-2">
            <Label for="role">{{ t('admin.users.form.labels.role') }}</Label>
            <Select v-model="role">
              <SelectTrigger :class="errors.role ? 'border-destructive' : ''">
                <SelectValue :placeholder="t('admin.users.form.placeholders.selectRole')" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="admin">{{ t('dashboard.roles.admin') }}</SelectItem>
                <SelectItem value="user">{{ t('dashboard.roles.user') }}</SelectItem>
              </SelectContent>
            </Select>
            <p v-if="errors.role" class="text-destructive text-sm">{{ errors.role }}</p>
          </div>
          
          <!-- Image field -->
          <div class="space-y-2">
            <Label for="image">{{ t('admin.users.form.labels.image') }}</Label>
            <Input 
              id="image"
              v-bind="imageAttrs"
              v-model="image"
              :placeholder="t('admin.users.form.placeholders.image')"
              :class="errors.image ? 'border-destructive' : ''"
            />
            <p v-if="errors.image" class="text-destructive text-sm">{{ errors.image }}</p>
          </div>

          <!-- Phone number field -->
          <div class="space-y-2">
            <Label for="phoneNumber">{{ t('admin.users.form.labels.phoneNumber') }}</Label>
            <Input 
              id="phoneNumber"
              v-bind="phoneNumberAttrs"
              v-model="phoneNumber"
              :placeholder="t('admin.users.form.placeholders.phoneNumber')"
              :class="errors.phoneNumber ? 'border-destructive' : ''"
            />
            <p v-if="errors.phoneNumber" class="text-destructive text-sm">{{ errors.phoneNumber }}</p>
          </div>

          <!-- Email verified toggle -->
          <div class="flex items-center justify-between">
            <Label for="emailVerified" class="font-semibold">
              {{ t('admin.users.form.labels.emailVerified') }}
            </Label>
            <Switch v-model="emailVerified" />
          </div>

          <!-- Phone verified toggle -->
          <div class="flex items-center justify-between">
            <Label for="phoneNumberVerified" class="font-semibold">
              {{ t('admin.users.form.labels.phoneVerified') }}
            </Label>
            <Switch v-model="phoneNumberVerified" />
          </div>

          <!-- Banned toggle -->
          <div class="flex items-center justify-between">
            <Label for="banned" class="font-semibold">
              {{ t('admin.users.form.labels.banned') }}
            </Label>
            <Switch v-model="banned" />
          </div>
          
          <!-- Ban reason field -->
          <div class="space-y-2">
            <Label for="banReason">{{ t('admin.users.form.labels.banReason') }}</Label>
            <Input 
              id="banReason"
              v-bind="banReasonAttrs"
              v-model="banReason"
              :placeholder="t('admin.users.form.placeholders.banReason')"
              :class="errors.banReason ? 'border-destructive' : ''"
            />
            <p v-if="errors.banReason" class="text-destructive text-sm">{{ errors.banReason }}</p>
          </div>
        </CardContent>
        <CardFooter class="flex justify-between space-x-4 pt-6">
          <div class="flex space-x-4">
            <Button 
              type="submit" 
              :disabled="isSubmitting"
              class="flex items-center gap-2"
            >
              <Save class="h-4 w-4" />
              {{ isSubmitting ? t('common.loading') : (isEditMode ? t('actions.saveChanges') : t('actions.createUser')) }}
            </Button>
            
            <!-- Delete button (only for edit mode) -->
            <AlertDialog v-if="isEditMode">
              <AlertDialogTrigger as-child>
                <Button variant="destructive" type="button" class="flex items-center gap-2">
                  <Trash2 class="h-4 w-4" />
                  {{ t('actions.deleteUser') }}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>{{ t('admin.users.deleteDialog.title') }}</AlertDialogTitle>
                  <AlertDialogDescription>
                    {{ t('admin.users.deleteDialog.description') }}
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>{{ t('actions.cancel') }}</AlertDialogCancel>
                  <AlertDialogAction 
                    @click="handleDelete"
                    class="bg-destructive hover:bg-destructive/90"
                  >
                    {{ t('actions.delete') }}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </CardFooter>
      </Card>
    </form>
  </div>
</template>

<script setup lang="ts">
import { Save, Trash2 } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { authClientVue } from '@libs/auth/authClient'
import { createAdminUserValidators } from '@libs/validators'
import { useForm } from 'vee-validate'
import type { z } from 'zod'

// Define page metadata
definePageMeta({
  layout: 'admin'
  // No middleware needed - auth.global.ts handles admin routes automatically
})

// Get route params and composables
const route = useRoute()
const router = useRouter()
const { t } = useI18n()

const userId = route.params.id as string
const isEditMode = userId !== 'new'

// Create validators with translation function
const { createAdminUserFormSchema, updateAdminUserFormSchema } = createAdminUserValidators(t)

// Choose the appropriate schema based on mode
const validationSchema = computed(() => {
  return isEditMode ? updateAdminUserFormSchema : createAdminUserFormSchema
})

// Setup form with VeeValidate
const { 
  handleSubmit, 
  errors, 
  defineField,
  setValues,
  resetForm
} = useForm({
  validationSchema: validationSchema.value,
  initialValues: {
    name: '',
    email: '',
    password: '',
    role: 'user',
    image: '',
    phoneNumber: '',
    emailVerified: false,
    phoneNumberVerified: false,
    banned: false,
    banReason: ''
  }
})

// Define form fields with VeeValidate
const [name, nameAttrs] = defineField('name')
const [email, emailAttrs] = defineField('email')
const [password, passwordAttrs] = defineField('password')
const [role, roleAttrs] = defineField('role')
const [image, imageAttrs] = defineField('image')
const [phoneNumber, phoneNumberAttrs] = defineField('phoneNumber')
const [banReason, banReasonAttrs] = defineField('banReason')

// Define boolean fields separately (VeeValidate doesn't handle these well with defineField)
const emailVerified = ref(false)
const phoneNumberVerified = ref(false)
const banned = ref(false)

// Loading and error states
const pending = ref(false)
const isSubmitting = ref(false)
const errorMessage = ref('')

// Define types for API responses
interface UserData {
  id: string
  name: string
  email: string
  role: 'user' | 'admin'
  image?: string | null
  phoneNumber?: string | null
  emailVerified: boolean
  phoneNumberVerified: boolean
  banned: boolean
  banReason?: string | null
}

// Fetch user data for edit mode
let userData: Ref<UserData | undefined> = ref(undefined)

if (isEditMode) {
  const { data } = await useFetch<UserData>(`/api/users/${userId}`, {
    server: false,
    onRequest() {
      pending.value = true
    },
    onResponse({ response }) {
      pending.value = false
      if (response._data) {
        const data = response._data
        // Set form values using VeeValidate
        setValues({
          name: data.name || '',
          email: data.email || '',
          role: (data.role as 'user' | 'admin') || 'user',
          image: data.image || '',
          phoneNumber: data.phoneNumber || '',
          banReason: data.banReason || ''
        })
        
        // Set boolean values separately
        emailVerified.value = data.emailVerified || false
        phoneNumberVerified.value = data.phoneNumberVerified || false
        banned.value = data.banned || false
      }
    },
    onResponseError({ error }) {
      pending.value = false
      errorMessage.value = error?.message || t('admin.users.messages.fetchError')
    }
  })
  userData = data
}

// Form submission with VeeValidate
const onSubmit = handleSubmit(async (values) => {
  isSubmitting.value = true
  errorMessage.value = ''

  try {
    // Prepare form data
    const formData = {
      ...values,
      emailVerified: emailVerified.value,
      phoneNumberVerified: phoneNumberVerified.value,
      banned: banned.value
    }

    // Debug: Log the form data being sent
    console.log('Form data being sent:', formData)

    if (isEditMode) {
      // Update all user data through single API call
      await $fetch(`/api/users/${userId}`, {
        method: 'PATCH',
        body: formData,
      })

      toast.success(t('admin.users.messages.updateSuccess'))
    } else {
      // Create user
      const { data, error } = await authClientVue.admin.createUser({
        name: formData.name,
        email: formData.email,
        password: formData.password || '',
        role: formData.role as 'admin' | 'user',
        data: {
          image: formData.image || undefined,
          phoneNumber: formData.phoneNumber || undefined,
          emailVerified: formData.emailVerified,
          phoneNumberVerified: formData.phoneNumberVerified,
          banned: formData.banned,
          banReason: formData.banReason || undefined,
        },
      })

      if (error) {
        toast.error(error.message || t('admin.users.messages.createError'))
        return
      }

      toast.success(t('admin.users.messages.createSuccess'))
    }

    // Navigate back to users list
    await router.push('/admin/users')
  } catch (error: any) {
    const message = error?.message || t('admin.users.messages.operationFailed')
    errorMessage.value = message
    toast.error(message)
  } finally {
    isSubmitting.value = false
  }
})

// Delete user
const handleDelete = async () => {
  const { data, error } = await authClientVue.admin.removeUser({
    userId,
  })
  
  if (error) {
    const message = error.message || t('admin.users.messages.deleteError')
    errorMessage.value = message
    toast.error(message)
    return
  }
  
  toast.success(t('admin.users.messages.deleteSuccess'))
  await router.push('/admin/users')
}

// Set page title
useHead({
  title: computed(() => isEditMode ? t('admin.users.editUser') : t('admin.users.createUser'))
})
</script>

// apps/next-app/app/[lang]/admin/users/[id]/page.tsx
'use client';

import { use } from 'react'
import { useEffect, useState } from 'react'
import { notFound, useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import { userRoles } from '@libs/database/constants'
import Link from 'next/link'
import { SaveIcon, Trash2Icon } from 'lucide-react'
import { authClientReact } from "@libs/auth/authClient"
import { useForm, Controller } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { createValidators } from "@libs/validators"
import { z } from "zod"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { toast } from "sonner"
import { Skeleton } from "@/components/ui/skeleton"
import { useTranslation } from "@/hooks/use-translation"



interface UserPageProps {
  params: Promise<{
    id?: string
  }>
}

export default function UserPage({ params }: UserPageProps) {
  const { t, tWithParams } = useTranslation();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const resolvedParams = use(params);
  const { id } = resolvedParams;
  const isEditMode = id !== 'new';

  // 创建国际化验证器
  const { userSchema, emailSignUpSchema, updateUserSchema } = createValidators(tWithParams);

  // 创建用户schema（包含密码字段）
  const createUserSchema = emailSignUpSchema.extend({
    image: z.string().url().optional().or(z.literal('')),
    role: z.enum([userRoles.ADMIN, userRoles.USER]).default(userRoles.USER),
    phoneNumber: z.string().nullable().optional(),
    emailVerified: z.boolean().default(false),
    phoneNumberVerified: z.boolean().default(false),
    banned: z.boolean().default(false),
    banReason: z.string().nullable().optional(),
  });

  type CreateUserFormData = z.infer<typeof createUserSchema>;
  type UpdateUserFormData = z.infer<typeof updateUserSchema>;

  const {
    register,
    handleSubmit,
    control,
    reset,
    formState: { errors }
  } = useForm<CreateUserFormData | UpdateUserFormData>({
    resolver: zodResolver(isEditMode ? updateUserSchema : createUserSchema),
    defaultValues: {
      role: userRoles.USER,
      emailVerified: false,
      phoneNumberVerified: false,
      banned: false,
    },
    mode: 'onBlur',
  });

  useEffect(() => {
    const fetchUser = async () => {
      if (id === 'new') {
        setLoading(false);
        return;
      }

      if (!id) {
        notFound();
      }

      try {
        const response = await fetch(`/api/users/${id}`);
        if (!response.ok) {
          throw new Error(t.admin.users.messages.fetchError);
        }
        const userData = await response.json();
        reset(userData);
        setLoading(false);
      } catch (err) {
        setError(err instanceof Error ? err.message : t.admin.users.messages.fetchError);
        notFound();
      }
    };

    fetchUser();
  }, [id, reset, t]);

  const onSubmit = async (data: CreateUserFormData | UpdateUserFormData) => {
    setError(null);

    try {
      if (isEditMode && id) {
        // Update user through API (handles all fields including role and ban status)
        await fetch(`/api/users/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data),
        });

        toast.success(t.admin.users.messages.updateSuccess);
      } else {
        // Create user
        const createData = data as CreateUserFormData;
        const { data: result, error } = await authClientReact.admin.createUser({
          name: createData.name,
          email: createData.email,
          password: createData.password,
          role: createData.role,
          data: {
            image: createData.image || undefined,
            phoneNumber: createData.phoneNumber || undefined,
            emailVerified: createData.emailVerified,
            phoneNumberVerified: createData.phoneNumberVerified,
            banned: createData.banned,
            banReason: createData.banReason || undefined,
          },
        });

        if (error) {
          const errorMessage = error.message || t.admin.users.messages.operationFailed;
          setError(errorMessage);
          toast.error(errorMessage);
          return;
        }

        toast.success(t.admin.users.messages.createSuccess);
      }

      router.push('/admin/users');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : t.admin.users.messages.operationFailed;
      setError(errorMessage);
      toast.error(errorMessage);
    }
  };

  const handleDelete = async () => {
    const { data, error } = await authClientReact.admin.removeUser({
      userId: id as string,
    });
    
    if (error) {
      const errorMessage = error.message || t.admin.users.messages.deleteError;
      setError(errorMessage);
      toast.error(errorMessage);
      return;
    }
    
    toast.success(t.admin.users.messages.deleteSuccess);
    router.push('/admin/users');
  };

  if (loading) {
    return (
      <div className="container mx-auto p-10">
        <div className="mb-6">
          <Skeleton className="h-6 w-32" />
        </div>

        <Skeleton className="h-10 w-60 mb-6" />

        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <Skeleton className="h-7 w-40 mb-2" />
            <Skeleton className="h-4 w-60" />
          </CardHeader>
          <CardContent className="space-y-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="space-y-2">
                <Skeleton className="h-5 w-24" />
                <Skeleton className="h-10 w-full" />
              </div>
            ))}
          </CardContent>
          <CardFooter className="pt-6">
            <Skeleton className="h-10 w-32" />
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-10">
      <div className="flex items-center mb-6">
        <Link href="/admin/users" className="text-blue-500 hover:text-blue-700">
          ← {t.actions.backToList}
        </Link>
      </div>

      <h1 className="text-3xl font-bold mb-6">
        {isEditMode ? t.admin.users.editUser : t.admin.users.createUser}
      </h1>

      {error && (
        <div className="mb-4 p-4 text-red-700 bg-red-100 rounded-md">
          {error}
        </div>
      )}

      <form 
        onSubmit={handleSubmit(onSubmit)}
        className="max-w-2xl mx-auto"
      >
        <Card>
          <CardHeader>
            <CardTitle>{t.admin.users.form.title}</CardTitle>
            <CardDescription>{t.admin.users.form.description}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">{t.admin.users.form.labels.name}</Label>
              <Input 
                id="name"
                {...register('name')}
                className={errors.name ? "border-red-500" : ""}
              />
              {errors.name && (
                <p className="text-red-500 text-sm">{errors.name.message}</p>
              )}
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="email">{t.admin.users.form.labels.email}</Label>
              <Input 
                id="email"
                type="email"
                {...register('email')}
                disabled={isEditMode}
                className={errors.email ? "border-red-500" : ""}
              />
              {errors.email && (
                <p className="text-red-500 text-sm">{errors.email.message}</p>
              )}
            </div>
            
            {!isEditMode && (
              <div className="space-y-2">
                <Label htmlFor="password">{t.admin.users.form.labels.password}</Label>
                <Input 
                  id="password"
                  type="password"
                  {...register('password')}
                  className={errors['password' as keyof typeof errors] ? "border-red-500" : ""}
                />
                {errors['password' as keyof typeof errors] && (
                  <p className="text-red-500 text-sm">
                    {errors['password' as keyof typeof errors]?.message}
                  </p>
                )}
              </div>
            )}
            
            <div className="space-y-2">
              <Label htmlFor="role">{t.admin.users.form.labels.role}</Label>
              <Controller
                name="role"
                control={control}
                render={({ field }) => (
                  <Select
                    onValueChange={field.onChange}
                    defaultValue={field.value}
                  >
                    <SelectTrigger className={errors.role ? "border-red-500" : ""}>
                      <SelectValue placeholder={t.admin.users.form.placeholders.selectRole} />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value={userRoles.ADMIN}>{userRoles.ADMIN}</SelectItem>
                      <SelectItem value={userRoles.USER}>{userRoles.USER}</SelectItem>
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.role && (
                <p className="text-red-500 text-sm">{errors.role.message}</p>
              )}
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="image">{t.admin.users.form.labels.image}</Label>
              <Input 
                id="image"
                {...register('image')}
                className={errors.image ? "border-red-500" : ""}
              />
              {errors.image && (
                <p className="text-red-500 text-sm">{errors.image.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="phoneNumber">{t.admin.users.form.labels.phoneNumber}</Label>
              <Input 
                id="phoneNumber"
                {...register('phoneNumber')}
                className={errors.phoneNumber ? "border-red-500" : ""}
              />
              {errors.phoneNumber && (
                <p className="text-red-500 text-sm">{errors.phoneNumber.message}</p>
              )}
            </div>

            <div className="flex items-center justify-between">
              <Label htmlFor="emailVerified" className="font-semibold">
                {t.admin.users.form.labels.emailVerified}
              </Label>
              <Controller
                name="emailVerified"
                control={control}
                render={({ field }) => (
                  <Switch 
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                )}
              />
            </div>

            <div className="flex items-center justify-between">
              <Label htmlFor="phoneNumberVerified" className="font-semibold">
                {t.admin.users.form.labels.phoneVerified}
              </Label>
              <Controller
                name="phoneNumberVerified"
                control={control}
                render={({ field }) => (
                  <Switch 
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                )}
              />
            </div>

            <div className="flex items-center justify-between">
              <Label htmlFor="banned" className="font-semibold">
                {t.admin.users.form.labels.banned}
              </Label>
              <Controller
                name="banned"
                control={control}
                render={({ field }) => (
                  <Switch 
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                )}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="banReason">{t.admin.users.form.labels.banReason}</Label>
              <Input 
                id="banReason"
                {...register('banReason')}
                className={errors.banReason ? "border-red-500" : ""}
              />
              {errors.banReason && (
                <p className="text-red-500 text-sm">{errors.banReason.message}</p>
              )}
            </div>
          </CardContent>
          <CardFooter className="flex justify-between space-x-4 pt-6">
            <div className="flex space-x-4">
              <Button 
                type="submit" 
                className="flex items-center gap-2"
              >
                <SaveIcon className="h-4 w-4" />
                {isEditMode ? t.actions.saveChanges : t.actions.createUser}
              </Button>
              
              {isEditMode && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button variant="destructive" type="button" className="flex items-center gap-2">
                      <Trash2Icon className="h-4 w-4" />
                      {t.actions.deleteUser}
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>{t.admin.users.deleteDialog.title}</AlertDialogTitle>
                      <AlertDialogDescription>
                        {t.admin.users.deleteDialog.description}
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>{t.actions.cancel}</AlertDialogCancel>
                      <AlertDialogAction 
                        onClick={handleDelete}
                        className="bg-red-600 hover:bg-red-700"
                      >
                        {t.actions.delete}
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
            </div>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
