// apps/nuxt-app/components/admin/users/columns.tsx
import { h } from 'vue'
import type { ColumnDef } from '@tanstack/vue-table'
import { Copy } from 'lucide-vue-next'
import type { Composer } from 'vue-i18n'
import UsersActionsCell from '@/components/admin/users/UsersActionsCell.vue'
import UsersBannedCell from '@/components/admin/users/UsersBannedCell.vue'
import UsersRoleCell from '@/components/admin/users/UsersRoleCell.vue'
import SortableHeader from '@/components/admin/SortableHeader.vue'

// User type definition based on the API response
export interface User {
  id: string
  name: string | null
  email: string
  role: string // Changed from 'admin' | 'user' to string to match API
  emailVerified: boolean
  banned: boolean | null // Changed to match API (can be null)
  createdAt: string | Date // Can be Date from API
  updatedAt: string | Date // Can be Date from API
}

// Table columns definition factory function
// Accepts t function from useI18n() to avoid calling useI18n() in render functions
export const createColumns = (t: Composer['t']): ColumnDef<User>[] => [
  // ID Column (hidden by default, no sorting needed)
  {
    accessorKey: 'id',
    header: () => {
      return <span>{t('admin.users.table.columns.id')}</span>
    },
    cell: ({ row }) => {
      const id = row.getValue('id') as string
      
      // Create tooltip content with copy functionality
      const copyToClipboard = async () => {
        try {
          await navigator.clipboard.writeText(id)
          // You could add a toast notification here
          console.log('ID copied to clipboard:', id)
        } catch (err) {
          console.error('Failed to copy ID:', err)
        }
      }
      
      return (
        <div class="group relative">
          {/* Main ID display */}
          <div 
            class="font-mono text-xs w-[180px] truncate cursor-pointer"
            onClick={copyToClipboard}
          >
            {id}
          </div>
          
          {/* Tooltip that appears on hover */}
          <div class="absolute z-50 hidden group-hover:block top-full left-0 pt-1">
            <div class="bg-popover text-popover-foreground shadow-md rounded-md border p-2 text-xs font-mono min-w-max">
              <div class="flex items-center gap-2">
                <span class="select-all">{id}</span>
                <button
                  class="p-1 hover:bg-accent rounded"
                  onClick={copyToClipboard}
                >
                  <Copy class="h-3 w-3" />
                </button>
              </div>
              <div class="text-xs text-muted-foreground mt-1">Click to copy</div>
            </div>
          </div>
        </div>
      )
    },
    enableSorting: false,
  },
  
  // Name Column (sortable - useful for alphabetical order)
  {
    accessorKey: 'name',
    header: ({ column }) => {
      return h(SortableHeader, {
        column,
        title: t('admin.users.table.columns.name'),
        ascendingText: t('admin.users.table.sort.ascending'),
        descendingText: t('admin.users.table.sort.descending'),
        noneText: t('admin.users.table.sort.none')
      })
    },
    cell: ({ row }) => {
      const name = row.getValue('name') as string | null
      return <div class="font-medium">{name || 'N/A'}</div>
    },
  },
  
  // Email Column (sortable - useful for alphabetical order)
  {
    accessorKey: 'email',
    header: ({ column }) => {
      return h(SortableHeader, {
        column,
        title: t('admin.users.table.columns.email'),
        ascendingText: t('admin.users.table.sort.ascending'),
        descendingText: t('admin.users.table.sort.descending'),
        noneText: t('admin.users.table.sort.none')
      })
    },
    cell: ({ row }) => {
      const email = row.getValue('email') as string
      return <div class="text-sm">{email}</div>
    },
  },
  
  // Role Column (with dropdown to change role)
  {
    accessorKey: 'role',
    header: () => {
      return <span>{t('admin.users.table.columns.role')}</span>
    },
    cell: ({ row, table }) => {
      const currentRole = row.getValue('role') as string
      const userId = row.getValue('id') as string
      
      // Get the onUserUpdated function from table meta
      const meta = table.options.meta as any
      const onUserUpdated = meta?.onUserUpdated
      
      return h(UsersRoleCell, { 
        currentRole,
        userId,
        onUserUpdated
      })
    },
    enableSorting: false,
  },
  
  // Phone Number Column
  {
    accessorKey: 'phoneNumber',
    header: () => {
      return <span>{t('admin.users.table.columns.phoneNumber')}</span>
    },
    cell: ({ row }) => {
      const phoneNumber = row.getValue('phoneNumber') as string | null
      return <div class="text-sm text-muted-foreground">{phoneNumber || 'N/A'}</div>
    },
    enableSorting: false,
  },
  
  // Email Verified Column (no sorting needed - just status display)
  {
    accessorKey: 'emailVerified',
    header: () => {
      return <span>{t('admin.users.table.columns.emailVerified')}</span>
    },
    cell: ({ row }) => {
      const verified = row.getValue('emailVerified') as boolean
      
      if (verified) {
        return (
          <div class="text-foreground">
            ✓ Verified
          </div>
        )
      }
      
      return (
        <div class="text-muted-foreground">
          ✗ Not verified
        </div>
      )
    },
    enableSorting: false,
  },
  
  // Banned Status Column (with toggle switch)
  {
    accessorKey: 'banned',
    header: () => {
      return <span>{t('admin.users.table.columns.banned')}</span>
    },
    cell: ({ row, table }) => {
      const bannedValue = row.getValue('banned') as boolean | null
      // Convert null to false for the switch (null means not banned)
      const isBanned = bannedValue === true
      const userId = row.getValue('id') as string
      
      // Get the onUserUpdated function from table meta to update local data
      const meta = table.options.meta as any
      const onUserUpdated = meta?.onUserUpdated
      
      return h(UsersBannedCell, { 
        value: isBanned,
        userId,
        onUserUpdated
      })
    },
    enableSorting: false,
  },
  
  // Created At Column (sortable - very useful for chronological order)
  {
    accessorKey: 'createdAt',
    header: ({ column }) => {
      return h(SortableHeader, {
        column,
        title: t('admin.users.table.columns.createdAt'),
        ascendingText: t('admin.users.table.sort.ascending'),
        descendingText: t('admin.users.table.sort.descending'),
        noneText: t('admin.users.table.sort.none')
      })
    },
    cell: ({ row }) => {
      const createdAt = row.getValue('createdAt') as string | Date
      const date = new Date(createdAt)
      const formatted = date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
      return <div class="text-sm text-muted-foreground">{formatted}</div>
    },
  },
  
  // Updated At Column (sortable - useful to see recent activity)
  {
    accessorKey: 'updatedAt',
    header: ({ column }) => {
      return h(SortableHeader, {
        column,
        title: t('admin.users.table.columns.updatedAt'),
        ascendingText: t('admin.users.table.sort.ascending'),
        descendingText: t('admin.users.table.sort.descending'),
        noneText: t('admin.users.table.sort.none')
      })
    },
    cell: ({ row }) => {
      const updatedAt = row.getValue('updatedAt') as string | Date
      const date = new Date(updatedAt)
      const formatted = date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
      return <div class="text-sm text-muted-foreground">{formatted}</div>
    },
  },
  
  // Actions Column (no sorting)
  {
    id: 'actions',
    header: () => {
      return <div class="text-center">{t('admin.users.table.columns.actions')}</div>
    },
    cell: ({ row, table }) => {
      const user = row.original
      
      // Get the onUserUpdated and onUserDeleted functions from table meta
      const meta = table.options.meta as any
      const onUserUpdated = meta?.onUserUpdated
      const onUserDeleted = meta?.onUserDeleted
      
      return h('div', { class: 'flex justify-center' }, 
        h(UsersActionsCell, { 
          user,
          'onUser-updated': onUserUpdated,
          'onUser-deleted': onUserDeleted
        })
      )
    },
    enableSorting: false,
    enableHiding: false,
  },
]

// Export default columns for backward compatibility (will be created in component setup)
export const columns: ColumnDef<User>[] = []

// apps/next-app/app/[lang]/admin/orders/columns.tsx
"use client"

import { ColumnDef } from "@tanstack/react-table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { MoreHorizontal, ArrowUpDown, Copy, ExternalLink, RefreshCw, ArrowUp, ArrowDown } from "lucide-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import { useTranslation } from "@/hooks/use-translation"

export type Order = {
  id: string
  userId: string
  amount: string
  currency: string
  planId: string
  status: string
  provider: string
  providerOrderId?: string | null
  metadata?: any
  createdAt: string | Date
  updatedAt?: string | Date
  // 关联的用户信息
  userName?: string | null
  userEmail?: string | null
}

const getStatusBadge = (status: string, t: any) => {
  const statusConfig = {
    pending: { label: t.admin.orders.table.search.pending, variant: "outline" as const },
    paid: { label: t.admin.orders.table.search.paid, variant: "default" as const },
    failed: { label: t.admin.orders.table.search.failed, variant: "destructive" as const },
    refunded: { label: t.admin.orders.table.search.refunded, variant: "secondary" as const },
    canceled: { label: t.admin.orders.table.search.canceled, variant: "secondary" as const },
  }
  
  const config = statusConfig[status as keyof typeof statusConfig] || { label: status, variant: "outline" as const }
  return <Badge variant={config.variant}>{config.label}</Badge>
}

const getProviderBadge = (provider: string, t: any) => {
  const providerConfig = {
    stripe: { label: t.admin.orders.table.search.stripe, variant: "outline" as const },
    wechat: { label: t.admin.orders.table.search.wechat, variant: "outline" as const },
    creem: { label: t.admin.orders.table.search.creem, variant: "outline" as const },
  }
  
  const config = providerConfig[provider as keyof typeof providerConfig] || { label: provider, variant: "outline" as const }
  return <Badge variant={config.variant}>{config.label}</Badge>
}

const formatDate = (date: string | Date | null) => {
  if (!date) return 'N/A'
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatAmount = (amount: string, currency: string) => {
  const numAmount = parseFloat(amount)
  if (isNaN(numAmount)) return `${currency} ${amount}`
  
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency.toUpperCase(),
    minimumFractionDigits: 2
  }).format(numAmount)
}

// Sortable header component
const SortableHeader = ({ column, title, t }: { column: any, title: string, t: any }) => {
  const sortDirection = column.getIsSorted()
  
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost"
          className="h-auto p-0 font-medium hover:bg-transparent hover:text-accent-foreground flex items-center"
        >
          {title}
          <div className="ml-2 flex flex-col">
            {sortDirection === "asc" ? (
              <ArrowUp className="h-3 w-3" />
            ) : sortDirection === "desc" ? (
              <ArrowDown className="h-3 w-3" />
            ) : (
              <ArrowUpDown className="h-3 w-3" />
            )}
          </div>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start">
        <DropdownMenuItem onClick={() => column.toggleSorting(false)}>
          <ArrowUp className="mr-2 h-4 w-4" />
          {t.admin.orders.table.sort.ascending}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => column.toggleSorting(true)}>
          <ArrowDown className="mr-2 h-4 w-4" />
          {t.admin.orders.table.sort.descending}
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={() => column.clearSorting()}>
          <ArrowUpDown className="mr-2 h-4 w-4" />
          {t.admin.orders.table.sort.none}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export const useOrderColumns = (): ColumnDef<Order>[] => {
  const { t } = useTranslation()

  return [
    {
      accessorKey: "id",
      header: t.admin.orders.table.columns.id,
      cell: ({ row }) => {
        const id = row.getValue("id") as string
        
        const copyToClipboard = async () => {
          try {
            await navigator.clipboard.writeText(id)
            console.log('Order ID copied to clipboard:', id)
          } catch (err) {
            console.error('Failed to copy Order ID:', err)
          }
        }
        
        return (
          <div className="group relative">
            <div 
              className="font-mono text-sm max-w-[100px] truncate cursor-pointer"
              title={id}
              onClick={copyToClipboard}
            >
              #{id.slice(-8)}
            </div>
            
            {/* Tooltip */}
            <div className="absolute z-50 hidden group-hover:block top-full left-0 pt-1">
              <div className="bg-popover text-popover-foreground shadow-md rounded-md border p-2 text-xs font-mono min-w-max">
                <div className="flex items-center gap-2">
                  <span className="select-all">{id}</span>
                  <button 
                    className="p-1 hover:bg-accent rounded"
                    onClick={copyToClipboard}
                  >
                    <Copy className="h-3 w-3" />
                  </button>
                </div>
                <div className="text-xs text-muted-foreground mt-1">
                  {t.admin.orders.table.actions.clickToCopy}
                </div>
              </div>
            </div>
          </div>
        )
      },
      enableSorting: false,
    },
    {
      accessorKey: "userEmail",
      header: ({ column }) => {
        return <SortableHeader column={column} title={t.admin.orders.table.columns.user} t={t} />
      },
      cell: ({ row }) => {
        const email = row.getValue("userEmail") as string
        const name = row.original.userName
        return (
          <div className="max-w-[150px]">
            <div className="font-medium truncate text-foreground" title={name || t.common.notAvailable}>
              {name || t.common.notAvailable}
            </div>
            <div className="text-sm text-muted-foreground truncate" title={email || t.common.notAvailable}>
              {email || t.common.notAvailable}
            </div>
          </div>
        )
      },
      enableHiding: false,
    },
    {
      accessorKey: "amount",
      header: ({ column }) => {
        return <SortableHeader column={column} title={t.admin.orders.table.columns.amount} t={t} />
      },
      cell: ({ row }) => {
        const amount = row.getValue("amount") as string
        const currency = row.original.currency
        return <div className="font-medium text-foreground">{formatAmount(amount, currency)}</div>
      },
      enableHiding: false,
    },
    {
      accessorKey: "planId",
      header: t.admin.orders.table.columns.plan,
      cell: ({ row }) => {
        const planId = row.getValue("planId") as string
        return <div className="font-medium">{planId || t.common.notAvailable}</div>
      },
      enableSorting: false,
    },
    {
      accessorKey: "status",
      header: t.admin.orders.table.columns.status,
      cell: ({ row }) => getStatusBadge(row.getValue("status"), t),
      enableHiding: false,
      enableSorting: false,
    },
    {
      accessorKey: "provider",
      header: t.admin.orders.table.columns.provider,
      cell: ({ row }) => getProviderBadge(row.getValue("provider"), t),
      enableHiding: false,
      enableSorting: false,
    },
    {
      accessorKey: "providerOrderId",
      header: t.admin.orders.table.columns.providerOrderId,
      cell: ({ row }) => {
        const providerOrderId = row.getValue("providerOrderId") as string
        return (
          <div className="font-mono text-xs max-w-[120px] truncate" title={providerOrderId || t.common.notAvailable}>
            {providerOrderId || t.common.notAvailable}
          </div>
        )
      },
      enableSorting: false,
    },
    {
      accessorKey: "createdAt",
      header: ({ column }) => {
        return <SortableHeader column={column} title={t.admin.orders.table.columns.createdAt} t={t} />
      },
      cell: ({ row }) => {
        const date = row.getValue("createdAt") as string | Date | null
        return <div className="text-sm text-muted-foreground">{formatDate(date)}</div>
      },
    },
    // {
    //   id: "actions",
    //   header: () => <div className="text-center">{t.admin.orders.table.columns.actions}</div>,
    //   cell: ({ row }) => {
    //     const order = row.original

    //     return (
    //       <DropdownMenu>
    //         <DropdownMenuTrigger asChild>
    //           <Button variant="ghost" className="h-8 w-8 p-0">
    //             <span className="sr-only">{t.admin.orders.table.actions.openMenu}</span>
    //             <MoreHorizontal className="h-4 w-4" />
    //           </Button>
    //         </DropdownMenuTrigger>
    //         <DropdownMenuContent align="end">
    //           <DropdownMenuLabel>{t.admin.orders.table.actions.actions}</DropdownMenuLabel>
    //           <DropdownMenuItem 
    //             onClick={() => {
    //               // TODO: Implement view order functionality
    //               console.log('View order:', order.id)
    //             }}
    //           >
    //             <ExternalLink className="mr-2 h-4 w-4" />
    //             {t.admin.orders.table.actions.viewOrder}
    //           </DropdownMenuItem>
    //           <DropdownMenuItem 
    //             onClick={() => {
    //               // TODO: Implement refund functionality
    //               console.log('Refund order:', order.id)
    //             }}
    //             disabled={order.status !== 'paid'}
    //           >
    //             <RefreshCw className="mr-2 h-4 w-4" />
    //             {t.admin.orders.table.actions.refundOrder}
    //           </DropdownMenuItem>
    //         </DropdownMenuContent>
    //       </DropdownMenu>
    //     )
    //   },
    //   enableHiding: false,
    //   enableSorting: false,
    // },
  ]
}

// 为了向后兼容，保留原来的导出
export const columns: ColumnDef<Order>[] = []
