// apps/nuxt-app/pages/cellphone.vue
<template>
  <div>
    <Card class="w-[380px]">
      <CardHeader class="text-center">
        <CardTitle class="text-xl">{{ t('auth.phone.title') }}</CardTitle>
        <CardDescription>
          {{ t('auth.phone.description') }}
        </CardDescription>
      </CardHeader>
      <CardContent class="flex flex-col gap-6">
        <PhoneLoginForm />
        <div class="text-muted-foreground text-center text-xs text-balance [&_a]:underline [&_a]:underline-offset-4 [&_a:hover]:text-primary">
          {{ t('auth.phone.termsNotice') }} <a href="#">{{ t('auth.phone.termsOfService') }}</a>
          {{ t('common.and') }} <a href="#">{{ t('auth.phone.privacyPolicy') }}</a>.
        </div>
        <div class="flex justify-center gap-4 text-sm">
          <NuxtLink :to="localePath('/signin')" class="text-primary hover:underline">
            {{ t('auth.signin.title') }}
          </NuxtLink>
          <span class="text-muted-foreground">|</span>
          <NuxtLink :to="localePath('/signup')" class="text-primary hover:underline">
            {{ t('auth.signup.createAccount') }}
          </NuxtLink>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

// Set page metadata
definePageMeta({
  layout: 'auth',
  title: 'Phone Login'
})

// Get i18n composable
const { t } = useI18n()

// Get localized path function
const localePath = useLocalePath()

// Set page head with reactive translations
useHead({
  title: () => t('auth.metadata.phone.title'),
  meta: [
    { name: 'description', content: () => t('auth.metadata.phone.description') },
    { name: 'keywords', content: () => t('auth.metadata.phone.keywords') }
  ]
})
</script>

// apps/next-app/app/[lang]/(auth)/cellphone/page.tsx
'use client';

import Link from 'next/link';
import { PhoneLoginForm } from "@/components/phone-login-form"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useTranslation } from "@/hooks/use-translation"

export default function LoginPage() {
  const { t, locale } = useTranslation()

  return (
    <Card className="w-[380px]">
      <CardHeader className="text-center">
        <CardTitle className="text-xl">{t.auth.phone.title}</CardTitle>
        <CardDescription>
          {t.auth.phone.description}
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-6">
        <PhoneLoginForm />
        <div className="text-muted-foreground text-center text-xs text-balance [&_a]:underline [&_a]:underline-offset-4 [&_a:hover]:text-primary">
          {t.auth.phone.termsNotice} <a href="#">{t.auth.phone.termsOfService}</a>{" "}
          {t.common.and} <a href="#">{t.auth.phone.privacyPolicy}</a>.
        </div>
        <div className="flex justify-center gap-4 text-sm">
          <Link href={`/${locale}/signin`} className="text-primary hover:underline">
            {t.auth.signin.title}
          </Link>
          <span className="text-muted-foreground">|</span>
          <Link href={`/${locale}/signup`} className="text-primary hover:underline">
            {t.auth.signup.createAccount}
          </Link>
        </div>
      </CardContent>
    </Card>
  )
}
