// apps/nuxt-app/components/SignupForm.vue
<template>
  <!-- 
    SignupForm.vue - Registration form component
    Features:
    - User registration form (name, email, password, avatar)
    - Form validation (using vee-validate + zod)
    - Error handling display
    - Captcha verification support
    - Email verification prompt after successful registration
    - Internationalization support
    - Better-Auth integration
  -->
  
      <!-- Email verification prompt state -->
  <div v-if="isVerificationEmailSent && requireEmailVerification" :class="cn('flex flex-col gap-4', className)">
    <Alert class="my-4">
      <Inbox class="h-4 w-4" />
      <AlertTitle>{{ t('auth.signup.verification.title') }}</AlertTitle>
      <AlertDescription class="mt-2">
        <p class="mb-2">
          {{ t('auth.signup.verification.sent') }} <strong>{{ verificationEmail }}</strong>.
        </p>
        <p class="text-sm text-muted-foreground">
          {{ t('auth.signup.verification.checkSpam') }}
          {{ t('auth.signup.verification.spamInstruction') }}
          <Button
            variant="link"
            @click="showResendDialog = true" 
          >
            {{ t('actions.tryAgain') }}
          </Button>
        </p>
      </AlertDescription>
    </Alert>
    
    <ResendVerificationDialog
      :is-open="showResendDialog"
      :email="verificationEmail"
      @close="showResendDialog = false"
    />
  </div>

      <!-- Registration form -->
    <div v-else :class="cn('flex flex-col gap-4', className)">
      <!-- Display error message -->
    <FormError v-if="errorMessage" :message="errorMessage" :code="errorCode" />
    
    <form @submit="onSubmit" class="flex flex-col gap-4">
      <div class="grid gap-6">
        <!-- Name input -->
        <div class="grid gap-2">
          <Label for="name">{{ t('auth.signup.name') }}</Label>
          <div class="relative">
            <Input
              id="name"
              v-bind="nameAttrs"
              v-model="name"
              type="text"
              :placeholder="t('auth.signup.namePlaceholder')"
              :class="cn(errors.name && 'border-destructive')"
              :aria-invalid="errors.name ? 'true' : 'false'"
              autocomplete="name"
            />
            <span v-if="errors.name" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.name }}
            </span>
          </div>
        </div>

                  <!-- Email input -->
        <div class="grid gap-2">
          <Label for="email">{{ t('auth.signup.email') }}</Label>
          <div class="relative">
            <Input
              id="email"
              v-bind="emailAttrs"
              v-model="email"
              type="email"
              :placeholder="t('auth.signup.emailPlaceholder')"
              :class="cn(errors.email && 'border-destructive')"
              :aria-invalid="errors.email ? 'true' : 'false'"
              autocomplete="email"
            />
            <span v-if="errors.email" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.email }}
            </span>
          </div>
        </div>

                  <!-- Password input -->
        <div class="grid gap-2">
          <Label for="password">{{ t('auth.signup.password') }}</Label>
          <div class="relative">
            <Input
              id="password"
              v-bind="passwordAttrs"
              v-model="password"
              type="password"
              :placeholder="t('auth.signup.passwordPlaceholder')"
              :class="cn(errors.password && 'border-destructive')"
              :aria-invalid="errors.password ? 'true' : 'false'"
              autocomplete="new-password"
            />
            <span v-if="errors.password" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.password }}
            </span>
          </div>
        </div>

                  <!-- Avatar URL input (optional) -->
        <div class="grid gap-2">
          <Label for="image">
            {{ t('auth.signup.imageUrl') }} ({{ t('auth.signup.optional') }})
          </Label>
          <div class="relative">
            <Input
              id="image"
              v-bind="imageAttrs"
              v-model="image"
              type="url"
              :placeholder="t('auth.signup.imageUrlPlaceholder')"
              :class="cn(errors.image && 'border-destructive')"
              :aria-invalid="errors.image ? 'true' : 'false'"
            />
            <span v-if="errors.image" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.image }}
            </span>
          </div>
        </div>

        <!-- Captcha component (if enabled) -->
        <div v-if="captchaEnabled" class="grid gap-2">
          <VueTurnstile
            :key="turnstileKey"
            ref="turnstileRef"
            :site-key="captchaSiteKey"
            v-model="turnstileToken"
            size="flexible"
            @error="onTurnstileError"
            @expired="onTurnstileExpired"
            :theme="isDark ? 'dark' : 'light'"
          />
          <span v-if="turnstileError" class="text-destructive text-xs">
            {{ turnstileError }}
          </span>
        </div>

        <!-- Submit button -->
        <Button 
          type="submit" 
          class="w-full" 
          :disabled="loading || isSubmitting || (captchaEnabled && !turnstileToken)"
        >
          {{ loading ? t('auth.signup.submitting') : t('auth.signup.submit') }}
        </Button>
      </div>

      <!-- Login link -->
      <div class="text-center text-sm">
        {{ t('auth.signup.haveAccount') }}
        <NuxtLink :to="localePath('/signin')" class="text-primary hover:underline underline-offset-4">
          {{ t('auth.signup.signinLink') }}
        </NuxtLink>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { useForm } from 'vee-validate'
import { createValidators } from '@libs/validators'
import { authClientVue } from '@libs/auth/authClient'
import { cn } from '@/lib/utils'
import VueTurnstile from 'vue-turnstile'
import { Inbox } from 'lucide-vue-next'
import { config } from '@config'

interface Props {
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

// Initialize internationalization and navigation
const { t } = useI18n()
const localePath = useLocalePath()
const { locale } = useI18n()
const route = useRoute()

// State management
const loading = ref(false)
const errorMessage = ref('')
const errorCode = ref('')
const isVerificationEmailSent = ref(false)
const verificationEmail = ref('')
const showResendDialog = ref(false)

// Get runtime configuration
const runtimeConfig = useRuntimeConfig()

// Auth configuration - directly from config
const requireEmailVerification = config.auth.requireEmailVerification

// Captcha related state
const captchaEnabled = computed(() => {
  return runtimeConfig.public.captchaEnabled !== 'false'
})

const captchaSiteKey = computed(() => {
  const siteKey = runtimeConfig.public.turnstileSiteKey as string | undefined
  return siteKey || '1x00000000000000000000AA'
})

const turnstileToken = ref('')
const turnstileError = ref('')
const turnstileRef = ref()
const turnstileKey = ref(0) // Force re-render Turnstile

// Theme detection (simplified version)
const isDark = ref(false)

// Turnstile event handlers
const onTurnstileError = () => {
  turnstileError.value = t('auth.signup.errors.captchaError')
  turnstileToken.value = ''
}

const onTurnstileExpired = () => {
  turnstileError.value = t('auth.signup.errors.captchaExpired')
  turnstileToken.value = ''
}

// Create internationalized validators
const { signupFormSchema } = createValidators(t)

// Form validation
const { handleSubmit, errors, defineField, isSubmitting } = useForm({
  validationSchema: signupFormSchema,
  initialValues: {
    name: '',
    email: '',
    password: '',
    image: ''
  }
})

// Define form fields
const [name, nameAttrs] = defineField('name', {
  validateOnBlur: true
})
const [email, emailAttrs] = defineField('email', {
  validateOnBlur: true
})
const [password, passwordAttrs] = defineField('password', {
  validateOnBlur: true  
})
const [image, imageAttrs] = defineField('image', {
  validateOnBlur: true
})

// Handle form submission
const onSubmit = handleSubmit(async (values) => {
  // Validate captcha (if enabled)
  if (captchaEnabled.value && !turnstileToken.value) {
    errorMessage.value = t('auth.signup.errors.captchaRequired')
    return
  }

  loading.value = true
  errorMessage.value = ''
  errorCode.value = ''
  turnstileError.value = ''

  try {
    const fetchOptions: any = {}
    
    // If captcha is enabled, add captcha token to request headers
    if (captchaEnabled.value && turnstileToken.value) {
      fetchOptions.headers = {
        'x-captcha-response': turnstileToken.value
      }
    }

    const result = await authClientVue.signUp.email(
      {
        email: values.email,
        password: values.password,
        name: values.name,
        image: values.image || undefined,
      },
      fetchOptions
    )

    // Check for errors
    if (result && 'error' in result && result.error) {
      const error = result.error
      if (error.code) {
        // Use internationalized error messages
        const authErrorMessage = t('auth.authErrors.' + error.code) || t('auth.authErrors.UNKNOWN_ERROR')
        errorMessage.value = authErrorMessage
        errorCode.value = error.code
      } else {
        errorMessage.value = t('common.unexpectedError')
        errorCode.value = 'UNKNOWN_ERROR'
      }
      
      // If validation fails, reset turnstile token and force re-render
      if (captchaEnabled.value) {
        turnstileToken.value = ''
        turnstileKey.value += 1
      }
      
      loading.value = false
      return
    }

    console.log('Sign up successful', result)
    
    // Check if email verification is required
    if (requireEmailVerification) {
      // Show email verification prompt
      verificationEmail.value = values.email
      isVerificationEmailSent.value = true
    } else {
      // Redirect after successful signup, check for returnTo parameter
      const returnTo = route.query.returnTo as string
      if (returnTo) {
        // Redirect to the original page
        await navigateTo(returnTo)
      } else {
        // Default redirect to home page
        await navigateTo(localePath('/'))
      }
    }
    
    loading.value = false
  } catch (err) {
    errorMessage.value = t('common.unexpectedError')
    errorCode.value = 'UNEXPECTED_ERROR'
    loading.value = false
  }
})
</script>

// apps/next-app/components/signup-form.tsx
'use client';

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { authClientReact } from "@libs/auth/authClient";
import { createValidators } from "@libs/validators";
import type { z } from "zod";
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FormError } from "@/components/ui/form-error"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Turnstile } from "@/components/ui/turnstile"
import { ResendVerificationDialog } from "@/components/resend-verification-dialog"
import { Inbox } from "lucide-react"
import { useTranslation } from "@/hooks/use-translation"
import { config } from "@config"
import Link from "next/link"

export function SignupForm({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  const router = useRouter();
  const { t, locale, tWithParams } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [errorCode, setErrorCode] = useState('');
  const [isVerificationEmailSent, setIsVerificationEmailSent] = useState(false);
  const [verificationEmail, setVerificationEmail] = useState('');
  const [showResendDialog, setShowResendDialog] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
  const [turnstileKey, setTurnstileKey] = useState(0); // 用于强制重新渲染 Turnstile

  // 创建国际化验证器
  const { signupFormSchema } = createValidators(tWithParams);
  
  type FormData = z.infer<typeof signupFormSchema>;

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting }
  } = useForm<FormData>({
    resolver: zodResolver(signupFormSchema),
    defaultValues: {
      email: '',
      password: '',
      name: '',
      image: ''
    },
    mode: 'onBlur', // Enable validation on blur
  });

  const onSubmit = async (formData: FormData) => {
    // 如果启用了 captcha 但没有 token，则提示用户
    if (config.captcha.enabled && !turnstileToken) {
      setErrorMessage(t.auth.signup.errors.captchaRequired);
      return;
    }

    setLoading(true);
    setErrorMessage('');
    setErrorCode('');
    
    const { error, data } = await authClientReact.signUp.email(
      {
        email: formData.email,
        password: formData.password,
        name: formData.name,
        image: formData.image || undefined,
      },
      config.captcha.enabled && turnstileToken ? {
        headers: {
          "x-captcha-response": turnstileToken,
        },
      } : undefined
    );

    if (error) {
      if (error.code) {
        // Use internationalized error messages
        const authErrorMessage = t.auth.authErrors[error.code as keyof typeof t.auth.authErrors] || t.auth.authErrors.UNKNOWN_ERROR;
        setErrorMessage(authErrorMessage);
        setErrorCode(error.code);
      } else {
        setErrorMessage(t.common.unexpectedError);
        setErrorCode('UNKNOWN_ERROR');
      }
      // 如果验证失败，重置 turnstile token 并强制重新渲染
      if (config.captcha.enabled) {
        setTurnstileToken(null);
        setTurnstileKey(prev => prev + 1); // 强制重新渲染 Turnstile 组件
      }
      setLoading(false);
      return;
    }

    console.log('Sign up successful', data);
    
    // Check if email verification is required
    if (config.auth.requireEmailVerification) {
      // Show email verification prompt
      setVerificationEmail(formData.email);
      setIsVerificationEmailSent(true);
    } else {
      const params = new URLSearchParams(window.location.search);
      const returnTo = params.get('returnTo');
      router.push(returnTo || `/${locale}`);
    }
    
    setLoading(false);
  };

  if (isVerificationEmailSent && config.auth.requireEmailVerification) {
    return (
      <div className={cn("flex flex-col gap-4", className)} {...props}>
        <Alert className="my-4">
          <Inbox className="h-4 w-4" />
          <AlertTitle>{t.auth.signup.verification.title}</AlertTitle>
          <AlertDescription className="mt-2">
            <p className="mb-2">
              {t.auth.signup.verification.sent} <strong>{verificationEmail}</strong>.
            </p>
            <p className="text-sm text-muted-foreground">
              {t.auth.signup.verification.checkSpam}
              {t.auth.signup.verification.spamInstruction}
              <Button
                variant="link"
                onClick={() => setShowResendDialog(true)}
              >
                {t.actions.tryAgain}
              </Button>
            </p>
          </AlertDescription>
        </Alert>
        
        <ResendVerificationDialog
          isOpen={showResendDialog}
          onClose={() => setShowResendDialog(false)}
          email={verificationEmail}
        />
      </div>
    );
  }

  return (
    <div className={cn("flex flex-col gap-4", className)} {...props}>
      <FormError message={errorMessage} code={errorCode} />
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <div className="grid gap-6">
          <div className="grid gap-2">
            <Label htmlFor="name">{t.auth.signup.name}</Label>
            <div className="relative">
              <Input
                id="name"
                type="text"
                {...register('name')}
                placeholder={t.auth.signup.namePlaceholder}
                className={cn(errors.name && "border-destructive")}
                aria-invalid={errors.name ? "true" : "false"}
                autoComplete="name"
              />
              {errors.name && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.name.message}
                </span>
              )}
            </div>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="email">{t.auth.signup.email}</Label>
            <div className="relative">
              <Input
                id="email"
                type="email"
                {...register('email')}
                placeholder={t.auth.signup.emailPlaceholder}
                className={cn(errors.email && "border-destructive")}
                aria-invalid={errors.email ? "true" : "false"}
                autoComplete="email"
              />
              {errors.email && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.email.message}
                </span>
              )}
            </div>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="password">{t.auth.signup.password}</Label>
            <div className="relative">
              <Input
                id="password"
                type="password"
                {...register('password')}
                placeholder={t.auth.signup.passwordPlaceholder}
                className={cn(errors.password && "border-destructive")}
                aria-invalid={errors.password ? "true" : "false"}
                autoComplete="new-password"
              />
              {errors.password && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.password.message}
                </span>
              )}
            </div>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="image">
              {t.auth.signup.imageUrl} ({t.auth.signup.optional})
            </Label>
            <div className="relative">
              <Input
                id="image"
                type="url"
                {...register('image')}
                placeholder={t.auth.signup.imageUrlPlaceholder}
                className={cn(errors.image && "border-destructive")}
                aria-invalid={errors.image ? "true" : "false"}
              />
              {errors.image && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.image.message}
                </span>
              )}
            </div>
          </div>

          {/* Cloudflare Turnstile 验证码 */}
          <Turnstile
            key={turnstileKey}
            onSuccess={(token: string) => setTurnstileToken(token)}
            onError={() => setTurnstileToken(null)}
            onExpire={() => setTurnstileToken(null)}
          />

          <Button 
            type="submit" 
            className="w-full" 
            disabled={loading || isSubmitting || (config.captcha.enabled && !turnstileToken)}
          >
            {loading ? t.auth.signup.submitting : t.auth.signup.submit}
          </Button>
        </div>
        <div className="text-center text-sm">
          {t.auth.signup.haveAccount}{" "}
          <Link href={`/${locale}/signin`} className="text-primary hover:underline underline-offset-4">
            {t.auth.signup.signinLink}
          </Link>
        </div>
      </form>
    </div>
  );
}
